CXX_FLAGS = -fPIC -ggdb -m32
#CXX_FLAGS = -fPIC -O3 -m32
#CXX_FLAGS = -fPIC -ggdb 
#CXX_FLAGS = -fPIC -O3
LXX_FLAGS =  -L ../Thread -l Thread -L ../Transport -L ./ -l Transport -l RPC -l pthread
IXX_FLAGS = -I ../Transport -I ../Thread
OBJECTS := $(patsubst %.cpp,%.o, $(wildcard *.cpp))

all : test

test :
	$(CXX) -o test test.cpp $(CXX_FLAGS) $(IXX_FLAGS) $(LXX_FLAGS)

clean :
	-rm test 2>/dev/null

rebuild : clean test

	

	
