CXX = g++
#CXX_FLAGS = -fPIC -ggdb -m32
CXX_FLAGS = -fPIC -O3 -m32
#CXX_FLAGS = -fPIC -ggdb 
#CXX_FLAGS = -fPIC -O3
LXX_FLAGS = -l Transport -L .

all : test

test :
	$(CXX) -o test test.cpp $(CXX_FLAGS) $(LXX_FLAGS) 

clean :
	-rm -rf test test.o 2>/dev/null

rebuild : clean test

run : rebuild
	./test server :444 yop
	./test client 127.0.0.1:444 pouet
	

	
