var annotated_dup =
[
    [ "amalgamate", "namespaceamalgamate.html", [
      [ "Amalgamation", "classamalgamate_1_1_amalgamation.html", "classamalgamate_1_1_amalgamation" ],
      [ "TranslationUnit", "classamalgamate_1_1_translation_unit.html", "classamalgamate_1_1_translation_unit" ]
    ] ],
    [ "CSharpLog2Reporter", "namespace_c_sharp_log2_reporter.html", [
      [ "Logger", "class_c_sharp_log2_reporter_1_1_logger.html", null ]
    ] ],
    [ "detail", "namespacedetail.html", [
      [ "container_input_adapter_factory_impl", "namespacedetail_1_1container__input__adapter__factory__impl.html", [
        [ "container_input_adapter_factory", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
        [ "container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory_3c644ae35b641285039c4edb8bb512793.html", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory_3c644ae35b641285039c4edb8bb512793" ]
      ] ],
      [ "dtoa_impl", "namespacedetail_1_1dtoa__impl.html", [
        [ "boundaries", "structdetail_1_1dtoa__impl_1_1boundaries.html", "structdetail_1_1dtoa__impl_1_1boundaries" ],
        [ "cached_power", "structdetail_1_1dtoa__impl_1_1cached__power.html", "structdetail_1_1dtoa__impl_1_1cached__power" ],
        [ "diyfp", "structdetail_1_1dtoa__impl_1_1diyfp.html", "structdetail_1_1dtoa__impl_1_1diyfp" ]
      ] ],
      [ "utility_internal", "namespacedetail_1_1utility__internal.html", [
        [ "Extend", "structdetail_1_1utility__internal_1_1_extend.html", null ],
        [ "Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structdetail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints_8_8_8_01_4_00_01_seq_size_00_010_01_4.html", "structdetail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints_8_8_8_01_4_00_01_seq_size_00_010_01_4" ],
        [ "Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structdetail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints_8_8_8_01_4_00_01_seq_size_00_011_01_4.html", "structdetail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints_8_8_8_01_4_00_01_seq_size_00_011_01_4" ],
        [ "Gen", "structdetail_1_1utility__internal_1_1_gen.html", "structdetail_1_1utility__internal_1_1_gen" ],
        [ "Gen< T, 0 >", "structdetail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4.html", "structdetail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4" ]
      ] ],
      [ "actual_object_comparator", "structdetail_1_1actual__object__comparator.html", "structdetail_1_1actual__object__comparator" ],
      [ "binary_reader", "classdetail_1_1binary__reader.html", "classdetail_1_1binary__reader" ],
      [ "binary_writer", "classdetail_1_1binary__writer.html", "classdetail_1_1binary__writer" ],
      [ "char_traits", "structdetail_1_1char__traits.html", null ],
      [ "char_traits< signed char >", "structdetail_1_1char__traits_3_01signed_01char_01_4.html", "structdetail_1_1char__traits_3_01signed_01char_01_4" ],
      [ "char_traits< unsigned char >", "structdetail_1_1char__traits_3_01unsigned_01char_01_4.html", "structdetail_1_1char__traits_3_01unsigned_01char_01_4" ],
      [ "conjunction", "structdetail_1_1conjunction.html", null ],
      [ "conjunction< B >", "structdetail_1_1conjunction_3_01_b_01_4.html", null ],
      [ "conjunction< B, Bn... >", "structdetail_1_1conjunction_3_01_b_00_01_bn_8_8_8_01_4.html", null ],
      [ "detector", "structdetail_1_1detector.html", "structdetail_1_1detector" ],
      [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structdetail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4.html", "structdetail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4" ],
      [ "exception", "classdetail_1_1exception.html", "classdetail_1_1exception" ],
      [ "external_constructor", "structdetail_1_1external__constructor.html", null ],
      [ "external_constructor< value_t::array >", "structdetail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
      [ "external_constructor< value_t::binary >", "structdetail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
      [ "external_constructor< value_t::boolean >", "structdetail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
      [ "external_constructor< value_t::number_float >", "structdetail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
      [ "external_constructor< value_t::number_integer >", "structdetail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
      [ "external_constructor< value_t::number_unsigned >", "structdetail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
      [ "external_constructor< value_t::object >", "structdetail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
      [ "external_constructor< value_t::string >", "structdetail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
      [ "file_input_adapter", "classdetail_1_1file__input__adapter.html", "classdetail_1_1file__input__adapter" ],
      [ "from_json_fn", "structdetail_1_1from__json__fn.html", "structdetail_1_1from__json__fn" ],
      [ "has_from_json", "structdetail_1_1has__from__json.html", null ],
      [ "has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_9is__basic_fce8b8f93d45fb838eee91b696633019.html", "structdetail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_9is__basic_fce8b8f93d45fb838eee91b696633019" ],
      [ "has_key_compare", "structdetail_1_1has__key__compare.html", null ],
      [ "has_non_default_from_json", "structdetail_1_1has__non__default__from__json.html", null ],
      [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_2d17f33a54f009ebd0a99d19cdccdb1f.html", "structdetail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_2d17f33a54f009ebd0a99d19cdccdb1f" ],
      [ "has_to_json", "structdetail_1_1has__to__json.html", null ],
      [ "has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_9is__basic__j28a68f7ad118503a2d1e9663db2d9323.html", "structdetail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_9is__basic__j28a68f7ad118503a2d1e9663db2d9323" ],
      [ "identity_tag", "structdetail_1_1identity__tag.html", null ],
      [ "input_stream_adapter", "classdetail_1_1input__stream__adapter.html", "classdetail_1_1input__stream__adapter" ],
      [ "integer_sequence", "structdetail_1_1integer__sequence.html", "structdetail_1_1integer__sequence" ],
      [ "internal_iterator", "structdetail_1_1internal__iterator.html", "structdetail_1_1internal__iterator" ],
      [ "invalid_iterator", "classdetail_1_1invalid__iterator.html", null ],
      [ "is_basic_json", "structdetail_1_1is__basic__json.html", null ],
      [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structdetail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
      [ "is_basic_json_context", "structdetail_1_1is__basic__json__context.html", null ],
      [ "is_c_string", "structdetail_1_1is__c__string.html", null ],
      [ "is_comparable", "structdetail_1_1is__comparable.html", null ],
      [ "is_comparable< Compare, A, B, void_t< decltype(std::declval< Compare >()(std::declval< A >(), std::declval< B >())), decltype(std::declval< Compare >()(std::declval< B >(), std::declval< A >()))> >", "structdetail_1_1is__comparable_3_01_compare_00_01_a_00_01_b_00_01void__t_3_01decltype_07std_1_1d1335caac8ed6d774dd842c8360097f7d.html", null ],
      [ "is_compatible_array_type", "structdetail_1_1is__compatible__array__type.html", null ],
      [ "is_compatible_array_type_impl", "structdetail_1_1is__compatible__array__type__impl.html", null ],
      [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structdetail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compatible_array_ty5a05c25fff6f823ac88824a10a386dcf.html", null ],
      [ "is_compatible_integer_type", "structdetail_1_1is__compatible__integer__type.html", null ],
      [ "is_compatible_integer_type_impl", "structdetail_1_1is__compatible__integer__type__impl.html", null ],
      [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structdetail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_compatible_numb0041c726545da1e9f9d50a47e3f940c2.html", "structdetail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_compatible_numb0041c726545da1e9f9d50a47e3f940c2" ],
      [ "is_compatible_object_type", "structdetail_1_1is__compatible__object__type.html", null ],
      [ "is_compatible_object_type_impl", "structdetail_1_1is__compatible__object__type__impl.html", null ],
      [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structdetail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compatible_object_c9788cfc69b1e1eda6ea05aee660649a.html", "structdetail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compatible_object_c9788cfc69b1e1eda6ea05aee660649a" ],
      [ "is_compatible_string_type", "structdetail_1_1is__compatible__string__type.html", null ],
      [ "is_compatible_type", "structdetail_1_1is__compatible__type.html", null ],
      [ "is_compatible_type_impl", "structdetail_1_1is__compatible__type__impl.html", null ],
      [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structdetail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_type_00_01enablc5e6eb56f10e073702c6c152991f15b9.html", null ],
      [ "is_complete_type", "structdetail_1_1is__complete__type.html", null ],
      [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structdetail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
      [ "is_constructible", "structdetail_1_1is__constructible.html", null ],
      [ "is_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "is_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "is_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "is_constructible< std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "is_constructible_array_type", "structdetail_1_1is__constructible__array__type.html", null ],
      [ "is_constructible_array_type_impl", "structdetail_1_1is__constructible__array__type__impl.html", null ],
      [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_constructible_ar54e545c8083fe861c90a40ff938a22b7.html", "structdetail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_constructible_ar54e545c8083fe861c90a40ff938a22b7" ],
      [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_constructible_ar18eb1802aca5c2f462bc2d940e11156a.html", null ],
      [ "is_constructible_object_type", "structdetail_1_1is__constructible__object__type.html", null ],
      [ "is_constructible_object_type_impl", "structdetail_1_1is__constructible__object__type__impl.html", null ],
      [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structdetail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_constructible_oe3af2486927b63ecadb7a7d2ea385f2a.html", "structdetail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_constructible_oe3af2486927b63ecadb7a7d2ea385f2a" ],
      [ "is_constructible_string_type", "structdetail_1_1is__constructible__string__type.html", "structdetail_1_1is__constructible__string__type" ],
      [ "is_constructible_tuple", "structdetail_1_1is__constructible__tuple.html", null ],
      [ "is_constructible_tuple< T1, std::tuple< Args... > >", "structdetail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
      [ "is_default_constructible", "structdetail_1_1is__default__constructible.html", null ],
      [ "is_default_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "is_default_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "is_default_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
      [ "is_default_constructible< std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "is_detected_lazy", "structdetail_1_1is__detected__lazy.html", null ],
      [ "is_getable", "structdetail_1_1is__getable.html", null ],
      [ "is_iterator_of_multibyte", "structdetail_1_1is__iterator__of__multibyte.html", "structdetail_1_1is__iterator__of__multibyte" ],
      [ "is_iterator_traits", "structdetail_1_1is__iterator__traits.html", null ],
      [ "is_iterator_traits< iterator_traits< T > >", "structdetail_1_1is__iterator__traits_3_01iterator__traits_3_01_t_01_4_01_4.html", null ],
      [ "is_json_iterator_of", "structdetail_1_1is__json__iterator__of.html", null ],
      [ "is_json_iterator_of< BasicJsonType, typename BasicJsonType::const_iterator >", "structdetail_1_1is__json__iterator__of_3_01_basic_json_type_00_01typename_01_basic_json_type_1_1const__iterator_01_4.html", null ],
      [ "is_json_iterator_of< BasicJsonType, typename BasicJsonType::iterator >", "structdetail_1_1is__json__iterator__of_3_01_basic_json_type_00_01typename_01_basic_json_type_1_1iterator_01_4.html", null ],
      [ "is_json_ref", "structdetail_1_1is__json__ref.html", null ],
      [ "is_json_ref< json_ref< T > >", "structdetail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
      [ "is_ordered_map", "structdetail_1_1is__ordered__map.html", "structdetail_1_1is__ordered__map" ],
      [ "is_range", "structdetail_1_1is__range.html", null ],
      [ "is_sax", "structdetail_1_1is__sax.html", null ],
      [ "is_sax_static_asserts", "structdetail_1_1is__sax__static__asserts.html", null ],
      [ "is_specialization_of", "structdetail_1_1is__specialization__of.html", null ],
      [ "is_specialization_of< Primary, Primary< Args... > >", "structdetail_1_1is__specialization__of_3_01_primary_00_01_primary_3_01_args_8_8_8_01_4_01_4.html", null ],
      [ "is_transparent", "structdetail_1_1is__transparent.html", null ],
      [ "iter_impl", "classdetail_1_1iter__impl.html", "classdetail_1_1iter__impl" ],
      [ "iteration_proxy", "classdetail_1_1iteration__proxy.html", "classdetail_1_1iteration__proxy" ],
      [ "iteration_proxy_value", "classdetail_1_1iteration__proxy__value.html", "classdetail_1_1iteration__proxy__value" ],
      [ "iterator_input_adapter", "classdetail_1_1iterator__input__adapter.html", "classdetail_1_1iterator__input__adapter" ],
      [ "iterator_input_adapter_factory", "structdetail_1_1iterator__input__adapter__factory.html", "structdetail_1_1iterator__input__adapter__factory" ],
      [ "iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structdetail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__if__t_3_01is__5cecb9bc5a87721b11b4762b91835d89.html", "structdetail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__if__t_3_01is__5cecb9bc5a87721b11b4762b91835d89" ],
      [ "iterator_traits", "structdetail_1_1iterator__traits.html", null ],
      [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structdetail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01_t_01_4_1_1value_01_4_01_4.html", "structdetail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01_t_01_4_1_1value_01_4_01_4" ],
      [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structdetail_1_1iterator__traits_3_01_t_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01_t_01_4_1_1value_01_4_01_4.html", null ],
      [ "iterator_types", "structdetail_1_1iterator__types.html", null ],
      [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structdetail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1difference__type_00_064dac4a14931e9e3b7bc8e1311de4a39.html", "structdetail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1difference__type_00_064dac4a14931e9e3b7bc8e1311de4a39" ],
      [ "json_default_base", "structdetail_1_1json__default__base.html", null ],
      [ "json_ref", "classdetail_1_1json__ref.html", "classdetail_1_1json__ref" ],
      [ "json_reverse_iterator", "classdetail_1_1json__reverse__iterator.html", "classdetail_1_1json__reverse__iterator" ],
      [ "json_sax_acceptor", "classdetail_1_1json__sax__acceptor.html", "classdetail_1_1json__sax__acceptor" ],
      [ "json_sax_dom_callback_parser", "classdetail_1_1json__sax__dom__callback__parser.html", "classdetail_1_1json__sax__dom__callback__parser" ],
      [ "json_sax_dom_parser", "classdetail_1_1json__sax__dom__parser.html", "classdetail_1_1json__sax__dom__parser" ],
      [ "lexer", "classdetail_1_1lexer.html", "classdetail_1_1lexer" ],
      [ "lexer_base", "classdetail_1_1lexer__base.html", "classdetail_1_1lexer__base" ],
      [ "make_void", "structdetail_1_1make__void.html", "structdetail_1_1make__void" ],
      [ "negation", "structdetail_1_1negation.html", null ],
      [ "nonesuch", "structdetail_1_1nonesuch.html", "structdetail_1_1nonesuch" ],
      [ "other_error", "classdetail_1_1other__error.html", null ],
      [ "out_of_range", "classdetail_1_1out__of__range.html", null ],
      [ "output_adapter", "classdetail_1_1output__adapter.html", "classdetail_1_1output__adapter" ],
      [ "output_adapter_protocol", "structdetail_1_1output__adapter__protocol.html", "structdetail_1_1output__adapter__protocol" ],
      [ "output_stream_adapter", "classdetail_1_1output__stream__adapter.html", "classdetail_1_1output__stream__adapter" ],
      [ "output_string_adapter", "classdetail_1_1output__string__adapter.html", "classdetail_1_1output__string__adapter" ],
      [ "output_vector_adapter", "classdetail_1_1output__vector__adapter.html", "classdetail_1_1output__vector__adapter" ],
      [ "parse_error", "classdetail_1_1parse__error.html", "classdetail_1_1parse__error" ],
      [ "parser", "classdetail_1_1parser.html", "classdetail_1_1parser" ],
      [ "position_t", "structdetail_1_1position__t.html", "structdetail_1_1position__t" ],
      [ "primitive_iterator_t", "classdetail_1_1primitive__iterator__t.html", "classdetail_1_1primitive__iterator__t" ],
      [ "priority_tag", "structdetail_1_1priority__tag.html", null ],
      [ "priority_tag< 0 >", "structdetail_1_1priority__tag_3_010_01_4.html", null ],
      [ "serializer", "classdetail_1_1serializer.html", "classdetail_1_1serializer" ],
      [ "span_input_adapter", "classdetail_1_1span__input__adapter.html", "classdetail_1_1span__input__adapter" ],
      [ "static_const", "structdetail_1_1static__const.html", null ],
      [ "to_json_fn", "structdetail_1_1to__json__fn.html", "structdetail_1_1to__json__fn" ],
      [ "type_error", "classdetail_1_1type__error.html", null ],
      [ "value_in_range_of_impl1", "structdetail_1_1value__in__range__of__impl1.html", null ],
      [ "value_in_range_of_impl1< OfType, T, false >", "structdetail_1_1value__in__range__of__impl1_3_01_of_type_00_01_t_00_01false_01_4.html", null ],
      [ "value_in_range_of_impl1< OfType, T, true >", "structdetail_1_1value__in__range__of__impl1_3_01_of_type_00_01_t_00_01true_01_4.html", null ],
      [ "value_in_range_of_impl2", "structdetail_1_1value__in__range__of__impl2.html", null ],
      [ "value_in_range_of_impl2< OfType, T, false, false >", "structdetail_1_1value__in__range__of__impl2_3_01_of_type_00_01_t_00_01false_00_01false_01_4.html", null ],
      [ "value_in_range_of_impl2< OfType, T, false, true >", "structdetail_1_1value__in__range__of__impl2_3_01_of_type_00_01_t_00_01false_00_01true_01_4.html", null ],
      [ "value_in_range_of_impl2< OfType, T, true, false >", "structdetail_1_1value__in__range__of__impl2_3_01_of_type_00_01_t_00_01true_00_01false_01_4.html", null ],
      [ "value_in_range_of_impl2< OfType, T, true, true >", "structdetail_1_1value__in__range__of__impl2_3_01_of_type_00_01_t_00_01true_00_01true_01_4.html", null ],
      [ "wide_string_input_adapter", "classdetail_1_1wide__string__input__adapter.html", "classdetail_1_1wide__string__input__adapter" ],
      [ "wide_string_input_helper", "structdetail_1_1wide__string__input__helper.html", null ],
      [ "wide_string_input_helper< BaseInputAdapter, 2 >", "structdetail_1_1wide__string__input__helper_3_01_base_input_adapter_00_012_01_4.html", null ],
      [ "wide_string_input_helper< BaseInputAdapter, 4 >", "structdetail_1_1wide__string__input__helper_3_01_base_input_adapter_00_014_01_4.html", null ]
    ] ],
    [ "doctest", "namespacedoctest.html", [
      [ "detail", "namespacedoctest_1_1detail.html", [
        [ "types", "namespacedoctest_1_1detail_1_1types.html", [
          [ "enable_if", "structdoctest_1_1detail_1_1types_1_1enable__if.html", null ],
          [ "enable_if< true, T >", "structdoctest_1_1detail_1_1types_1_1enable__if_3_01true_00_01_t_01_4.html", "structdoctest_1_1detail_1_1types_1_1enable__if_3_01true_00_01_t_01_4" ],
          [ "false_type", "structdoctest_1_1detail_1_1types_1_1false__type.html", null ],
          [ "is_array", "structdoctest_1_1detail_1_1types_1_1is__array.html", null ],
          [ "is_array< T[SIZE]>", "structdoctest_1_1detail_1_1types_1_1is__array_3_01_t_0f_s_i_z_e_0e_4.html", null ],
          [ "is_enum", "structdoctest_1_1detail_1_1types_1_1is__enum.html", null ],
          [ "is_pointer", "structdoctest_1_1detail_1_1types_1_1is__pointer.html", null ],
          [ "is_pointer< T * >", "structdoctest_1_1detail_1_1types_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
          [ "is_rvalue_reference", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference.html", null ],
          [ "is_rvalue_reference< T && >", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference_3_01_t_01_6_6_01_4.html", null ],
          [ "remove_const", "structdoctest_1_1detail_1_1types_1_1remove__const.html", "structdoctest_1_1detail_1_1types_1_1remove__const" ],
          [ "remove_const< const T >", "structdoctest_1_1detail_1_1types_1_1remove__const_3_01const_01_t_01_4.html", "structdoctest_1_1detail_1_1types_1_1remove__const_3_01const_01_t_01_4" ],
          [ "remove_reference", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", "structdoctest_1_1detail_1_1types_1_1remove__reference" ],
          [ "remove_reference< T & >", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01_t_01_6_01_4.html", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01_t_01_6_01_4" ],
          [ "remove_reference< T && >", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01_t_01_6_6_01_4.html", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01_t_01_6_6_01_4" ],
          [ "true_type", "structdoctest_1_1detail_1_1types_1_1true__type.html", null ],
          [ "underlying_type", "structdoctest_1_1detail_1_1types_1_1underlying__type.html", "structdoctest_1_1detail_1_1types_1_1underlying__type" ]
        ] ],
        [ "ContextScope", "classdoctest_1_1detail_1_1_context_scope.html", "classdoctest_1_1detail_1_1_context_scope" ],
        [ "ContextScopeBase", "structdoctest_1_1detail_1_1_context_scope_base.html", "structdoctest_1_1detail_1_1_context_scope_base" ],
        [ "deferred_false", "structdoctest_1_1detail_1_1deferred__false.html", null ],
        [ "ExceptionTranslator", "classdoctest_1_1detail_1_1_exception_translator.html", "classdoctest_1_1detail_1_1_exception_translator" ],
        [ "Expression_lhs", "structdoctest_1_1detail_1_1_expression__lhs.html", "structdoctest_1_1detail_1_1_expression__lhs" ],
        [ "ExpressionDecomposer", "structdoctest_1_1detail_1_1_expression_decomposer.html", "structdoctest_1_1detail_1_1_expression_decomposer" ],
        [ "filldata", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "filldata< const char[N]>", "structdoctest_1_1detail_1_1filldata_3_01const_01char_0f_n_0e_4.html", null ],
        [ "filldata< const void * >", "structdoctest_1_1detail_1_1filldata_3_01const_01void_01_5_01_4.html", null ],
        [ "filldata< T * >", "structdoctest_1_1detail_1_1filldata_3_01_t_01_5_01_4.html", null ],
        [ "filldata< T[N]>", "structdoctest_1_1detail_1_1filldata_3_01_t_0f_n_0e_4.html", null ],
        [ "has_insertion_operator", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
        [ "has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>", "structdoctest_1_1detail_1_1has__insertion__operator_3_01_t_00_01decltype_07operator_3_3_07declvab094f732977dc5a8a6181e0b8269a776.html", null ],
        [ "IExceptionTranslator", "structdoctest_1_1detail_1_1_i_exception_translator.html", "structdoctest_1_1detail_1_1_i_exception_translator" ],
        [ "MessageBuilder", "structdoctest_1_1detail_1_1_message_builder.html", "structdoctest_1_1detail_1_1_message_builder" ],
        [ "RelationalComparator", "structdoctest_1_1detail_1_1_relational_comparator.html", "structdoctest_1_1detail_1_1_relational_comparator" ],
        [ "Result", "structdoctest_1_1detail_1_1_result.html", "structdoctest_1_1detail_1_1_result" ],
        [ "ResultBuilder", "structdoctest_1_1detail_1_1_result_builder.html", "structdoctest_1_1detail_1_1_result_builder" ],
        [ "should_stringify_as_underlying_type", "structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html", null ],
        [ "StringMakerBase", "structdoctest_1_1detail_1_1_string_maker_base.html", null ],
        [ "StringMakerBase< true >", "structdoctest_1_1detail_1_1_string_maker_base_3_01true_01_4.html", null ],
        [ "Subcase", "structdoctest_1_1detail_1_1_subcase.html", "structdoctest_1_1detail_1_1_subcase" ],
        [ "TestCase", "structdoctest_1_1detail_1_1_test_case.html", "structdoctest_1_1detail_1_1_test_case" ],
        [ "TestFailureException", "structdoctest_1_1detail_1_1_test_failure_exception.html", null ],
        [ "TestSuite", "structdoctest_1_1detail_1_1_test_suite.html", "structdoctest_1_1detail_1_1_test_suite" ]
      ] ],
      [ "Approx", "structdoctest_1_1_approx.html", "structdoctest_1_1_approx" ],
      [ "AssertData", "structdoctest_1_1_assert_data.html", "structdoctest_1_1_assert_data" ],
      [ "Contains", "classdoctest_1_1_contains.html", "classdoctest_1_1_contains" ],
      [ "Context", "classdoctest_1_1_context.html", "classdoctest_1_1_context" ],
      [ "ContextOptions", "structdoctest_1_1_context_options.html", "structdoctest_1_1_context_options" ],
      [ "CurrentTestCaseStats", "structdoctest_1_1_current_test_case_stats.html", "structdoctest_1_1_current_test_case_stats" ],
      [ "IContextScope", "structdoctest_1_1_i_context_scope.html", "structdoctest_1_1_i_context_scope" ],
      [ "IReporter", "structdoctest_1_1_i_reporter.html", "structdoctest_1_1_i_reporter" ],
      [ "IsNaN", "structdoctest_1_1_is_na_n.html", "structdoctest_1_1_is_na_n" ],
      [ "MessageData", "structdoctest_1_1_message_data.html", "structdoctest_1_1_message_data" ],
      [ "QueryData", "structdoctest_1_1_query_data.html", "structdoctest_1_1_query_data" ],
      [ "String", "classdoctest_1_1_string.html", "classdoctest_1_1_string" ],
      [ "StringMaker", "structdoctest_1_1_string_maker.html", null ],
      [ "SubcaseSignature", "structdoctest_1_1_subcase_signature.html", "structdoctest_1_1_subcase_signature" ],
      [ "TestCaseData", "structdoctest_1_1_test_case_data.html", "structdoctest_1_1_test_case_data" ],
      [ "TestCaseException", "structdoctest_1_1_test_case_exception.html", "structdoctest_1_1_test_case_exception" ],
      [ "TestRunStats", "structdoctest_1_1_test_run_stats.html", "structdoctest_1_1_test_run_stats" ]
    ] ],
    [ "ezRPC", "namespaceez_r_p_c.html", [
      [ "JsonCall", "classez_r_p_c_1_1_json_call.html", "classez_r_p_c_1_1_json_call" ],
      [ "JsonClientRpcWrapper", "classez_r_p_c_1_1_json_client_rpc_wrapper.html", "classez_r_p_c_1_1_json_client_rpc_wrapper" ],
      [ "JsonServerRpcWrapper", "classez_r_p_c_1_1_json_server_rpc_wrapper.html", "classez_r_p_c_1_1_json_server_rpc_wrapper" ],
      [ "Parameter", "classez_r_p_c_1_1_parameter.html", "classez_r_p_c_1_1_parameter" ]
    ] ],
    [ "fuzzer", "namespacefuzzer.html", [
      [ "Dictionary", "classfuzzer_1_1_dictionary.html", "classfuzzer_1_1_dictionary" ],
      [ "DictionaryEntry", "classfuzzer_1_1_dictionary_entry.html", "classfuzzer_1_1_dictionary_entry" ],
      [ "ExternalFunctions", "structfuzzer_1_1_external_functions.html", "structfuzzer_1_1_external_functions" ],
      [ "FixedWord", "classfuzzer_1_1_fixed_word.html", "classfuzzer_1_1_fixed_word" ],
      [ "FlagDescription", "structfuzzer_1_1_flag_description.html", "structfuzzer_1_1_flag_description" ],
      [ "Fuzzer", "classfuzzer_1_1_fuzzer.html", "classfuzzer_1_1_fuzzer" ],
      [ "FuzzingOptions", "structfuzzer_1_1_fuzzing_options.html", "structfuzzer_1_1_fuzzing_options" ],
      [ "InputCorpus", "classfuzzer_1_1_input_corpus.html", "classfuzzer_1_1_input_corpus" ],
      [ "InputInfo", "structfuzzer_1_1_input_info.html", "structfuzzer_1_1_input_info" ],
      [ "MallocFreeTracer", "structfuzzer_1_1_malloc_free_tracer.html", "structfuzzer_1_1_malloc_free_tracer" ],
      [ "MergeFileInfo", "structfuzzer_1_1_merge_file_info.html", "structfuzzer_1_1_merge_file_info" ],
      [ "Merger", "structfuzzer_1_1_merger.html", "structfuzzer_1_1_merger" ],
      [ "MutationDispatcher", "classfuzzer_1_1_mutation_dispatcher.html", "classfuzzer_1_1_mutation_dispatcher" ],
      [ "Random", "classfuzzer_1_1_random.html", "classfuzzer_1_1_random" ],
      [ "ScopedDoingMyOwnMemmem", "structfuzzer_1_1_scoped_doing_my_own_memmem.html", "structfuzzer_1_1_scoped_doing_my_own_memmem" ],
      [ "TableOfRecentCompares", "structfuzzer_1_1_table_of_recent_compares.html", "structfuzzer_1_1_table_of_recent_compares" ],
      [ "TraceBasedMutation", "structfuzzer_1_1_trace_based_mutation.html", "structfuzzer_1_1_trace_based_mutation" ],
      [ "TracePC", "classfuzzer_1_1_trace_p_c.html", "classfuzzer_1_1_trace_p_c" ],
      [ "TraceState", "classfuzzer_1_1_trace_state.html", "classfuzzer_1_1_trace_state" ],
      [ "ValueBitMap", "structfuzzer_1_1_value_bit_map.html", "structfuzzer_1_1_value_bit_map" ]
    ] ],
    [ "nlohmann", "namespacenlohmann.html", [
      [ "detail", "namespacenlohmann_1_1detail.html", [
        [ "container_input_adapter_factory_impl", "namespacenlohmann_1_1detail_1_1container__input__adapter__factory__impl.html", [
          [ "container_input_adapter_factory", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
          [ "container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adaptec6d36799bbab06a12576748f72ebcf00.html", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adaptec6d36799bbab06a12576748f72ebcf00" ]
        ] ],
        [ "dtoa_impl", "namespacenlohmann_1_1detail_1_1dtoa__impl.html", [
          [ "boundaries", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries" ],
          [ "cached_power", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power" ],
          [ "diyfp", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp" ]
        ] ],
        [ "utility_internal", "namespacenlohmann_1_1detail_1_1utility__internal.html", [
          [ "Extend", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend.html", null ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_intse4b696320406a0717efa9a961a507d9c.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_intse4b696320406a0717efa9a961a507d9c" ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints55b30810c0f772136f5c0a2221b86a09.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints55b30810c0f772136f5c0a2221b86a09" ],
          [ "Gen", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen" ],
          [ "Gen< T, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4" ]
        ] ],
        [ "binary_reader", "classnlohmann_1_1detail_1_1binary__reader.html", "classnlohmann_1_1detail_1_1binary__reader" ],
        [ "binary_writer", "classnlohmann_1_1detail_1_1binary__writer.html", "classnlohmann_1_1detail_1_1binary__writer" ],
        [ "conjunction", "structnlohmann_1_1detail_1_1conjunction.html", null ],
        [ "conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_01_4.html", null ],
        [ "conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b1_00_01_bn_8_8_8_01_4.html", null ],
        [ "detector", "structnlohmann_1_1detail_1_1detector.html", "structnlohmann_1_1detail_1_1detector" ],
        [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structnlohmann_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4.html", "structnlohmann_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4" ],
        [ "exception", "classnlohmann_1_1detail_1_1exception.html", "classnlohmann_1_1detail_1_1exception" ],
        [ "external_constructor", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
        [ "external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
        [ "external_constructor< value_t::binary >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
        [ "external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
        [ "external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
        [ "external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
        [ "external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
        [ "external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
        [ "external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
        [ "file_input_adapter", "classnlohmann_1_1detail_1_1file__input__adapter.html", "classnlohmann_1_1detail_1_1file__input__adapter" ],
        [ "from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", "structnlohmann_1_1detail_1_1from__json__fn" ],
        [ "has_from_json", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
        [ "has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896.html", "structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896" ],
        [ "has_non_default_from_json", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
        [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8.html", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8" ],
        [ "has_to_json", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
        [ "has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77.html", "structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77" ],
        [ "identity_tag", "structnlohmann_1_1detail_1_1identity__tag.html", null ],
        [ "input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", "classnlohmann_1_1detail_1_1input__stream__adapter" ],
        [ "integer_sequence", "structnlohmann_1_1detail_1_1integer__sequence.html", "structnlohmann_1_1detail_1_1integer__sequence" ],
        [ "internal_iterator", "structnlohmann_1_1detail_1_1internal__iterator.html", "structnlohmann_1_1detail_1_1internal__iterator" ],
        [ "invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "is_basic_json", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
        [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
        [ "is_compatible_array_type", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
        [ "is_compatible_array_type_impl", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
        [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compati4915acc171fa5fb7ebfebe0b9b6c0be2.html", null ],
        [ "is_compatible_integer_type", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
        [ "is_compatible_integer_type_impl", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
        [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604.html", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604" ],
        [ "is_compatible_object_type", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
        [ "is_compatible_object_type_impl", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
        [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5.html", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5" ],
        [ "is_compatible_string_type", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
        [ "is_compatible_type", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
        [ "is_compatible_type_impl", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
        [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_typ632bee7ec037fc0233f1bbe9dd7d8874.html", null ],
        [ "is_complete_type", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
        [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
        [ "is_constructible", "structnlohmann_1_1detail_1_1is__constructible.html", null ],
        [ "is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible_array_type", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
        [ "is_constructible_array_type_impl", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons27075d101b6ea0a206984ee0c21ea5d0.html", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons27075d101b6ea0a206984ee0c21ea5d0" ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
        [ "is_constructible_object_type", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
        [ "is_constructible_object_type_impl", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
        [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545.html", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545" ],
        [ "is_constructible_string_type", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ],
        [ "is_constructible_tuple", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
        [ "is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible", "structnlohmann_1_1detail_1_1is__default__constructible.html", null ],
        [ "is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_detected_lazy", "structnlohmann_1_1detail_1_1is__detected__lazy.html", null ],
        [ "is_getable", "structnlohmann_1_1detail_1_1is__getable.html", null ],
        [ "is_iterator_of_multibyte", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte.html", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte" ],
        [ "is_iterator_traits", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
        [ "is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01_t_01_4_01_4.html", null ],
        [ "is_json_ref", "structnlohmann_1_1detail_1_1is__json__ref.html", null ],
        [ "is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
        [ "is_ordered_map", "structnlohmann_1_1detail_1_1is__ordered__map.html", "structnlohmann_1_1detail_1_1is__ordered__map" ],
        [ "is_range", "structnlohmann_1_1detail_1_1is__range.html", null ],
        [ "is_sax", "structnlohmann_1_1detail_1_1is__sax.html", null ],
        [ "is_sax_static_asserts", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", null ],
        [ "iter_impl", "classnlohmann_1_1detail_1_1iter__impl.html", "classnlohmann_1_1detail_1_1iter__impl" ],
        [ "iteration_proxy", "classnlohmann_1_1detail_1_1iteration__proxy.html", "classnlohmann_1_1detail_1_1iteration__proxy" ],
        [ "iteration_proxy_value", "classnlohmann_1_1detail_1_1iteration__proxy__value.html", "classnlohmann_1_1detail_1_1iteration__proxy__value" ],
        [ "iterator_input_adapter", "classnlohmann_1_1detail_1_1iterator__input__adapter.html", "classnlohmann_1_1detail_1_1iterator__input__adapter" ],
        [ "iterator_input_adapter_factory", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory.html", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory" ],
        [ "iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__ifdbe9caa11c2ca51101ba1bbd1184c22c.html", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__ifdbe9caa11c2ca51101ba1bbd1184c22c" ],
        [ "iterator_traits", "structnlohmann_1_1detail_1_1iterator__traits.html", null ],
        [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__objec8d960665487688165530972cda4f1bea.html", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__objec8d960665487688165530972cda4f1bea" ],
        [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01_t_01_4_1_1value_01_4_01_4.html", null ],
        [ "iterator_types", "structnlohmann_1_1detail_1_1iterator__types.html", null ],
        [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structnlohmann_1_1detail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1differenc4a413e9bd546446175f10f15c5631361.html", "structnlohmann_1_1detail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1differenc4a413e9bd546446175f10f15c5631361" ],
        [ "json_ref", "classnlohmann_1_1detail_1_1json__ref.html", "classnlohmann_1_1detail_1_1json__ref" ],
        [ "json_reverse_iterator", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", "classnlohmann_1_1detail_1_1json__reverse__iterator" ],
        [ "json_sax_acceptor", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", "classnlohmann_1_1detail_1_1json__sax__acceptor" ],
        [ "json_sax_dom_callback_parser", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser" ],
        [ "json_sax_dom_parser", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__parser" ],
        [ "lexer", "classnlohmann_1_1detail_1_1lexer.html", "classnlohmann_1_1detail_1_1lexer" ],
        [ "lexer_base", "classnlohmann_1_1detail_1_1lexer__base.html", "classnlohmann_1_1detail_1_1lexer__base" ],
        [ "make_void", "structnlohmann_1_1detail_1_1make__void.html", "structnlohmann_1_1detail_1_1make__void" ],
        [ "negation", "structnlohmann_1_1detail_1_1negation.html", null ],
        [ "nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", "structnlohmann_1_1detail_1_1nonesuch" ],
        [ "other_error", "classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "output_adapter", "classnlohmann_1_1detail_1_1output__adapter.html", "classnlohmann_1_1detail_1_1output__adapter" ],
        [ "output_adapter_protocol", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", "structnlohmann_1_1detail_1_1output__adapter__protocol" ],
        [ "output_stream_adapter", "classnlohmann_1_1detail_1_1output__stream__adapter.html", "classnlohmann_1_1detail_1_1output__stream__adapter" ],
        [ "output_string_adapter", "classnlohmann_1_1detail_1_1output__string__adapter.html", "classnlohmann_1_1detail_1_1output__string__adapter" ],
        [ "output_vector_adapter", "classnlohmann_1_1detail_1_1output__vector__adapter.html", "classnlohmann_1_1detail_1_1output__vector__adapter" ],
        [ "parse_error", "classnlohmann_1_1detail_1_1parse__error.html", "classnlohmann_1_1detail_1_1parse__error" ],
        [ "parser", "classnlohmann_1_1detail_1_1parser.html", "classnlohmann_1_1detail_1_1parser" ],
        [ "position_t", "structnlohmann_1_1detail_1_1position__t.html", "structnlohmann_1_1detail_1_1position__t" ],
        [ "primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", "classnlohmann_1_1detail_1_1primitive__iterator__t" ],
        [ "priority_tag", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
        [ "priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
        [ "serializer", "classnlohmann_1_1detail_1_1serializer.html", "classnlohmann_1_1detail_1_1serializer" ],
        [ "span_input_adapter", "classnlohmann_1_1detail_1_1span__input__adapter.html", "classnlohmann_1_1detail_1_1span__input__adapter" ],
        [ "static_const", "structnlohmann_1_1detail_1_1static__const.html", null ],
        [ "to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", "structnlohmann_1_1detail_1_1to__json__fn" ],
        [ "type_error", "classnlohmann_1_1detail_1_1type__error.html", null ],
        [ "wide_string_input_adapter", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", "classnlohmann_1_1detail_1_1wide__string__input__adapter" ],
        [ "wide_string_input_helper", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 2 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_012_01_4.html", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 4 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_014_01_4.html", null ]
      ] ],
      [ "adl_serializer", "structnlohmann_1_1adl__serializer.html", null ],
      [ "adl_serializer< Foo >", "structnlohmann_1_1adl__serializer_3_01_foo_01_4.html", null ],
      [ "adl_serializer< NonDefaultConstructible >", "structnlohmann_1_1adl__serializer_3_01_non_default_constructible_01_4.html", null ],
      [ "adl_serializer< NonDefaultFromJsonStruct >", "structnlohmann_1_1adl__serializer_3_01_non_default_from_json_struct_01_4.html", null ],
      [ "adl_serializer< ns::person >", "structnlohmann_1_1adl__serializer_3_01ns_1_1person_01_4.html", null ],
      [ "adl_serializer< std::shared_ptr< T > >", "structnlohmann_1_1adl__serializer_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "adl_serializer< udt::legacy_type >", "structnlohmann_1_1adl__serializer_3_01udt_1_1legacy__type_01_4.html", null ],
      [ "basic_json", "classnlohmann_1_1basic__json.html", "classnlohmann_1_1basic__json" ],
      [ "byte_container_with_subtype", "classnlohmann_1_1byte__container__with__subtype.html", "classnlohmann_1_1byte__container__with__subtype" ],
      [ "fifo_map", "classnlohmann_1_1fifo__map.html", "classnlohmann_1_1fifo__map" ],
      [ "fifo_map_compare", "classnlohmann_1_1fifo__map__compare.html", "classnlohmann_1_1fifo__map__compare" ],
      [ "json_pointer", "classnlohmann_1_1json__pointer.html", "classnlohmann_1_1json__pointer" ],
      [ "json_sax", "structnlohmann_1_1json__sax.html", "structnlohmann_1_1json__sax" ],
      [ "ordered_map", "structnlohmann_1_1ordered__map.html", "structnlohmann_1_1ordered__map" ]
    ] ],
    [ "nlohmann-json", "namespacenlohmann-json.html", [
      [ "JsonValuePrinter", "classnlohmann-json_1_1_json_value_printer.html", "classnlohmann-json_1_1_json_value_printer" ]
    ] ],
    [ "ns", "namespacens.html", [
      [ "foo", "structns_1_1foo.html", "structns_1_1foo" ],
      [ "foo_serializer", "structns_1_1foo__serializer.html", null ],
      [ "foo_serializer< T, typename std::enable_if< !std::is_same< foo, T >::value >::type >", "structns_1_1foo__serializer_3_01_t_00_01typename_01std_1_1enable__if_3_01_9std_1_1is__same_3_01f46896d89d9a2165fde7843aa3d3a576d.html", null ],
      [ "foo_serializer< T, typename std::enable_if< std::is_same< foo, T >::value >::type >", "structns_1_1foo__serializer_3_01_t_00_01typename_01std_1_1enable__if_3_01std_1_1is__same_3_01foo14c66948e09468b967e750bd1007300d.html", null ],
      [ "person", "structns_1_1person.html", "structns_1_1person" ]
    ] ],
    [ "persons", "namespacepersons.html", [
      [ "person_with_private_alphabet", "classpersons_1_1person__with__private__alphabet.html", "classpersons_1_1person__with__private__alphabet" ],
      [ "person_with_private_data", "classpersons_1_1person__with__private__data.html", "classpersons_1_1person__with__private__data" ],
      [ "person_with_private_data_2", "classpersons_1_1person__with__private__data__2.html", "classpersons_1_1person__with__private__data__2" ],
      [ "person_with_public_alphabet", "classpersons_1_1person__with__public__alphabet.html", "classpersons_1_1person__with__public__alphabet" ],
      [ "person_without_default_constructor_1", "classpersons_1_1person__without__default__constructor__1.html", "classpersons_1_1person__without__default__constructor__1" ],
      [ "person_without_default_constructor_2", "classpersons_1_1person__without__default__constructor__2.html", "classpersons_1_1person__without__default__constructor__2" ],
      [ "person_without_private_data_1", "classpersons_1_1person__without__private__data__1.html", "classpersons_1_1person__without__private__data__1" ],
      [ "person_without_private_data_2", "classpersons_1_1person__without__private__data__2.html", "classpersons_1_1person__without__private__data__2" ],
      [ "person_without_private_data_3", "classpersons_1_1person__without__private__data__3.html", "classpersons_1_1person__without__private__data__3" ]
    ] ],
    [ "reporter", "namespacereporter.html", [
      [ "App", "classreporter_1_1_app.html", null ],
      [ "AppUtil", "classreporter_1_1_app_util.html", null ],
      [ "ARGBColorPanel", "classreporter_1_1_a_r_g_b_color_panel.html", "classreporter_1_1_a_r_g_b_color_panel" ],
      [ "ARGBColorPicker", "classreporter_1_1_a_r_g_b_color_picker.html", "classreporter_1_1_a_r_g_b_color_picker" ],
      [ "ColorCircle", "classreporter_1_1_color_circle.html", "classreporter_1_1_color_circle" ],
      [ "ContentFrame", "classreporter_1_1_content_frame.html", "classreporter_1_1_content_frame" ],
      [ "ContentFrameEnsemble", "classreporter_1_1_content_frame_ensemble.html", null ],
      [ "ContentFrameVE", "classreporter_1_1_content_frame_v_e.html", "classreporter_1_1_content_frame_v_e" ],
      [ "DecimalDigitsTextField", "classreporter_1_1_decimal_digits_text_field.html", "classreporter_1_1_decimal_digits_text_field" ],
      [ "FilePicker", "classreporter_1_1_file_picker.html", "classreporter_1_1_file_picker" ],
      [ "FindDialog", "classreporter_1_1_find_dialog.html", null ],
      [ "FindPanel", "classreporter_1_1_find_panel.html", "classreporter_1_1_find_panel" ],
      [ "GlobalSettingsPanel", "classreporter_1_1_global_settings_panel.html", "classreporter_1_1_global_settings_panel" ],
      [ "LineNumberDialog", "classreporter_1_1_line_number_dialog.html", null ],
      [ "LineNumberDialogVE", "classreporter_1_1_line_number_dialog_v_e.html", "classreporter_1_1_line_number_dialog_v_e" ],
      [ "LookAndFeelComboBox", "classreporter_1_1_look_and_feel_combo_box.html", "classreporter_1_1_look_and_feel_combo_box" ],
      [ "MainFrame", "classreporter_1_1_main_frame.html", "classreporter_1_1_main_frame" ],
      [ "MainFrameVE", "classreporter_1_1_main_frame_v_e.html", "classreporter_1_1_main_frame_v_e" ],
      [ "ModIdDefinitionDialog", "classreporter_1_1_mod_id_definition_dialog.html", null ],
      [ "ModIdDefinitionDialogVE", "classreporter_1_1_mod_id_definition_dialog_v_e.html", "classreporter_1_1_mod_id_definition_dialog_v_e" ],
      [ "ModIdTable", "classreporter_1_1_mod_id_table.html", "classreporter_1_1_mod_id_table" ],
      [ "ModIdTableModel", "classreporter_1_1_mod_id_table_model.html", "classreporter_1_1_mod_id_table_model" ],
      [ "ModIdTableTransferHandler", "classreporter_1_1_mod_id_table_transfer_handler.html", "classreporter_1_1_mod_id_table_transfer_handler" ],
      [ "MultiColoredTextArea", "classreporter_1_1_multi_colored_text_area.html", "classreporter_1_1_multi_colored_text_area" ],
      [ "ProgDefinitionDialog", "classreporter_1_1_prog_definition_dialog.html", null ],
      [ "ProgDefinitionDialogVE", "classreporter_1_1_prog_definition_dialog_v_e.html", "classreporter_1_1_prog_definition_dialog_v_e" ],
      [ "ProgTable", "classreporter_1_1_prog_table.html", "classreporter_1_1_prog_table" ],
      [ "ProgTableModel", "classreporter_1_1_prog_table_model.html", "classreporter_1_1_prog_table_model" ],
      [ "ProgTableTransferHandler", "classreporter_1_1_prog_table_transfer_handler.html", "classreporter_1_1_prog_table_transfer_handler" ],
      [ "Strings", "classreporter_1_1_strings.html", null ],
      [ "WindowNameDialog", "classreporter_1_1_window_name_dialog.html", null ],
      [ "WindowNameDialogVE", "classreporter_1_1_window_name_dialog_v_e.html", "classreporter_1_1_window_name_dialog_v_e" ],
      [ "WindowSettingsDialog", "classreporter_1_1_window_settings_dialog.html", "classreporter_1_1_window_settings_dialog" ]
    ] ],
    [ "serve_header", "namespaceserve__header.html", [
      [ "DirectoryEventBucket", "classserve__header_1_1_directory_event_bucket.html", "classserve__header_1_1_directory_event_bucket" ],
      [ "DualStackServer", "classserve__header_1_1_dual_stack_server.html", "classserve__header_1_1_dual_stack_server" ],
      [ "ExitHandler", "classserve__header_1_1_exit_handler.html", "classserve__header_1_1_exit_handler" ],
      [ "HeaderRequestHandler", "classserve__header_1_1_header_request_handler.html", "classserve__header_1_1_header_request_handler" ],
      [ "WorkTree", "classserve__header_1_1_work_tree.html", "classserve__header_1_1_work_tree" ],
      [ "WorkTrees", "classserve__header_1_1_work_trees.html", "classserve__header_1_1_work_trees" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "tr1", "namespacestd_1_1tr1.html", [
        [ "gtest_internal", "namespacestd_1_1tr1_1_1gtest__internal.html", [
          [ "AddRef", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref.html", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref" ],
          [ "AddRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4" ],
          [ "ByRef", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref" ],
          [ "ByRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4" ],
          [ "Get", "classstd_1_1tr1_1_1gtest__internal_1_1_get.html", null ],
          [ "Get< 0 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_010_01_4.html", null ],
          [ "Get< 1 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_011_01_4.html", null ],
          [ "Get< 2 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_012_01_4.html", null ],
          [ "Get< 3 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_013_01_4.html", null ],
          [ "Get< 4 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_014_01_4.html", null ],
          [ "Get< 5 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_015_01_4.html", null ],
          [ "Get< 6 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_016_01_4.html", null ],
          [ "Get< 7 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_017_01_4.html", null ],
          [ "Get< 8 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_018_01_4.html", null ],
          [ "Get< 9 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_019_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html", null ],
          [ "SameSizeTuplePrefixComparator< 0, 0 >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator< k, k >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html", null ],
          [ "TupleElement", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element.html", null ],
          [ "TupleElement< true, 0, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 1, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 2, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 3, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 4, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 5, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 6, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 7, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 8, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ],
          [ "TupleElement< true, 9, GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4" ]
        ] ],
        [ "tuple", "classstd_1_1tr1_1_1tuple.html", "classstd_1_1tr1_1_1tuple" ],
        [ "tuple<>", "classstd_1_1tr1_1_1tuple_3_4.html", "classstd_1_1tr1_1_1tuple_3_4" ],
        [ "tuple_element", "structstd_1_1tr1_1_1tuple__element.html", null ],
        [ "tuple_size", "structstd_1_1tr1_1_1tuple__size.html", null ],
        [ "tuple_size< GTEST_0_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__0___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_10_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_1_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__1___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_2_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__2___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_3_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__3___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_4_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__4___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_5_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__5___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_6_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__6___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_7_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__7___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_8_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__8___t_u_p_l_e___07_t_08_01_4.html", null ],
        [ "tuple_size< GTEST_9_TUPLE_(T) >", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__9___t_u_p_l_e___07_t_08_01_4.html", null ]
      ] ],
      [ "basic_istream", "classstd_1_1basic__istream.html", null ],
      [ "basic_ostream", "classstd_1_1basic__ostream.html", null ],
      [ "char_traits", "structstd_1_1char__traits.html", null ],
      [ "hash< nlohmann::NLOHMANN_BASIC_JSON_TPL >", "structstd_1_1hash_3_01nlohmann_1_1_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", "structstd_1_1hash_3_01nlohmann_1_1_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4" ],
      [ "less< ::nlohmann::detail::value_t >", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4.html", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4" ],
      [ "tuple", "classstd_1_1tuple.html", null ],
      [ "tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01_n_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", "classstd_1_1tuple__element_3_01_n_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4" ],
      [ "tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", null ]
    ] ],
    [ "testing", "namespacetesting.html", [
      [ "internal", "namespacetesting_1_1internal.html", [
        [ "AddReference", "structtesting_1_1internal_1_1_add_reference.html", "structtesting_1_1internal_1_1_add_reference" ],
        [ "AddReference< T & >", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4" ],
        [ "AssertHelper", "classtesting_1_1internal_1_1_assert_helper.html", "classtesting_1_1internal_1_1_assert_helper" ],
        [ "bool_constant", "structtesting_1_1internal_1_1bool__constant.html", "structtesting_1_1internal_1_1bool__constant" ],
        [ "CodeLocation", "structtesting_1_1internal_1_1_code_location.html", "structtesting_1_1internal_1_1_code_location" ],
        [ "CompileAssert", "structtesting_1_1internal_1_1_compile_assert.html", null ],
        [ "CompileAssertTypesEqual", "structtesting_1_1internal_1_1_compile_assert_types_equal.html", null ],
        [ "CompileAssertTypesEqual< T, T >", "structtesting_1_1internal_1_1_compile_assert_types_equal_3_01_t_00_01_t_01_4.html", null ],
        [ "ConstCharPtr", "structtesting_1_1internal_1_1_const_char_ptr.html", "structtesting_1_1internal_1_1_const_char_ptr" ],
        [ "ConstRef", "structtesting_1_1internal_1_1_const_ref.html", "structtesting_1_1internal_1_1_const_ref" ],
        [ "ConstRef< T & >", "structtesting_1_1internal_1_1_const_ref_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_const_ref_3_01_t_01_6_01_4" ],
        [ "EnableIf", "structtesting_1_1internal_1_1_enable_if.html", null ],
        [ "EnableIf< true >", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4.html", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4" ],
        [ "EqHelper", "classtesting_1_1internal_1_1_eq_helper.html", null ],
        [ "EqHelper< true >", "classtesting_1_1internal_1_1_eq_helper_3_01true_01_4.html", null ],
        [ "FloatingPoint", "classtesting_1_1internal_1_1_floating_point.html", "classtesting_1_1internal_1_1_floating_point" ],
        [ "FormatForComparison", "classtesting_1_1internal_1_1_format_for_comparison.html", null ],
        [ "FormatForComparison< ToPrint[N], OtherOperand >", "classtesting_1_1internal_1_1_format_for_comparison_3_01_to_print_0f_n_0e_00_01_other_operand_01_4.html", null ],
        [ "GTestLog", "classtesting_1_1internal_1_1_g_test_log.html", "classtesting_1_1internal_1_1_g_test_log" ],
        [ "GTestMutexLock", "classtesting_1_1internal_1_1_g_test_mutex_lock.html", "classtesting_1_1internal_1_1_g_test_mutex_lock" ],
        [ "HasValueType", "structtesting_1_1internal_1_1_has_value_type.html", null ],
        [ "HasValueType< T, VoidT< typename T::value_type > >", "structtesting_1_1internal_1_1_has_value_type_3_01_t_00_01_void_t_3_01typename_01_t_1_1value__type_01_4_01_4.html", null ],
        [ "ImplicitlyConvertible", "classtesting_1_1internal_1_1_implicitly_convertible.html", null ],
        [ "is_pointer", "structtesting_1_1internal_1_1is__pointer.html", null ],
        [ "is_pointer< T * >", "structtesting_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
        [ "is_same", "structtesting_1_1internal_1_1is__same.html", null ],
        [ "is_same< T, T >", "structtesting_1_1internal_1_1is__same_3_01_t_00_01_t_01_4.html", null ],
        [ "IsAProtocolMessage", "structtesting_1_1internal_1_1_is_a_protocol_message.html", null ],
        [ "IsHashTable", "structtesting_1_1internal_1_1_is_hash_table.html", null ],
        [ "IsRecursiveContainer", "structtesting_1_1internal_1_1_is_recursive_container.html", null ],
        [ "IsRecursiveContainerImpl", "structtesting_1_1internal_1_1_is_recursive_container_impl.html", null ],
        [ "IsRecursiveContainerImpl< C, false, HV >", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01false_00_01_h_v_01_4.html", null ],
        [ "IsRecursiveContainerImpl< C, true, false >", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01true_00_01false_01_4.html", null ],
        [ "IsRecursiveContainerImpl< C, true, true >", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01true_00_01true_01_4.html", "structtesting_1_1internal_1_1_is_recursive_container_impl_3_01_c_00_01true_00_01true_01_4" ],
        [ "IsSame", "structtesting_1_1internal_1_1_is_same.html", null ],
        [ "IsSame< T, T >", "structtesting_1_1internal_1_1_is_same_3_01_t_00_01_t_01_4.html", null ],
        [ "IteratorTraits", "structtesting_1_1internal_1_1_iterator_traits.html", "structtesting_1_1internal_1_1_iterator_traits" ],
        [ "IteratorTraits< const T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4" ],
        [ "IteratorTraits< T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4.html", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4" ],
        [ "linked_ptr", "classtesting_1_1internal_1_1linked__ptr.html", "classtesting_1_1internal_1_1linked__ptr" ],
        [ "linked_ptr_internal", "classtesting_1_1internal_1_1linked__ptr__internal.html", "classtesting_1_1internal_1_1linked__ptr__internal" ],
        [ "Mutex", "classtesting_1_1internal_1_1_mutex.html", "classtesting_1_1internal_1_1_mutex" ],
        [ "NativeArray", "classtesting_1_1internal_1_1_native_array.html", "classtesting_1_1internal_1_1_native_array" ],
        [ "ParameterizedTestCaseInfo", "classtesting_1_1internal_1_1_parameterized_test_case_info.html", "classtesting_1_1internal_1_1_parameterized_test_case_info" ],
        [ "ParameterizedTestCaseInfoBase", "classtesting_1_1internal_1_1_parameterized_test_case_info_base.html", "classtesting_1_1internal_1_1_parameterized_test_case_info_base" ],
        [ "ParameterizedTestCaseRegistry", "classtesting_1_1internal_1_1_parameterized_test_case_registry.html", "classtesting_1_1internal_1_1_parameterized_test_case_registry" ],
        [ "ParameterizedTestFactory", "classtesting_1_1internal_1_1_parameterized_test_factory.html", "classtesting_1_1internal_1_1_parameterized_test_factory" ],
        [ "ParamGenerator", "classtesting_1_1internal_1_1_param_generator.html", "classtesting_1_1internal_1_1_param_generator" ],
        [ "ParamGeneratorInterface", "classtesting_1_1internal_1_1_param_generator_interface.html", "classtesting_1_1internal_1_1_param_generator_interface" ],
        [ "ParamIterator", "classtesting_1_1internal_1_1_param_iterator.html", "classtesting_1_1internal_1_1_param_iterator" ],
        [ "ParamIteratorInterface", "classtesting_1_1internal_1_1_param_iterator_interface.html", "classtesting_1_1internal_1_1_param_iterator_interface" ],
        [ "ParamNameGenFunc", "structtesting_1_1internal_1_1_param_name_gen_func.html", "structtesting_1_1internal_1_1_param_name_gen_func" ],
        [ "Random", "classtesting_1_1internal_1_1_random.html", "classtesting_1_1internal_1_1_random" ],
        [ "RangeGenerator", "classtesting_1_1internal_1_1_range_generator.html", "classtesting_1_1internal_1_1_range_generator" ],
        [ "RE", "classtesting_1_1internal_1_1_r_e.html", "classtesting_1_1internal_1_1_r_e" ],
        [ "RelationToSourceCopy", "structtesting_1_1internal_1_1_relation_to_source_copy.html", null ],
        [ "RelationToSourceReference", "structtesting_1_1internal_1_1_relation_to_source_reference.html", null ],
        [ "RemoveConst", "structtesting_1_1internal_1_1_remove_const.html", "structtesting_1_1internal_1_1_remove_const" ],
        [ "RemoveConst< const T >", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4.html", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4" ],
        [ "RemoveConst< const T[N]>", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_0f_n_0e_4.html", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_0f_n_0e_4" ],
        [ "RemoveReference", "structtesting_1_1internal_1_1_remove_reference.html", "structtesting_1_1internal_1_1_remove_reference" ],
        [ "RemoveReference< T & >", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4" ],
        [ "RvalueRef", "structtesting_1_1internal_1_1_rvalue_ref.html", "structtesting_1_1internal_1_1_rvalue_ref" ],
        [ "scoped_ptr", "classtesting_1_1internal_1_1scoped__ptr.html", "classtesting_1_1internal_1_1scoped__ptr" ],
        [ "StaticAssertTypeEqHelper", "structtesting_1_1internal_1_1_static_assert_type_eq_helper.html", null ],
        [ "StaticAssertTypeEqHelper< T, T >", "structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html", null ],
        [ "String", "classtesting_1_1internal_1_1_string.html", null ],
        [ "TestFactoryBase", "classtesting_1_1internal_1_1_test_factory_base.html", "classtesting_1_1internal_1_1_test_factory_base" ],
        [ "TestFactoryImpl", "classtesting_1_1internal_1_1_test_factory_impl.html", "classtesting_1_1internal_1_1_test_factory_impl" ],
        [ "TestMetaFactory", "classtesting_1_1internal_1_1_test_meta_factory.html", "classtesting_1_1internal_1_1_test_meta_factory" ],
        [ "TestMetaFactoryBase", "classtesting_1_1internal_1_1_test_meta_factory_base.html", "classtesting_1_1internal_1_1_test_meta_factory_base" ],
        [ "ThreadLocal", "classtesting_1_1internal_1_1_thread_local.html", "classtesting_1_1internal_1_1_thread_local" ],
        [ "TuplePolicy", "structtesting_1_1internal_1_1_tuple_policy.html", null ],
        [ "TypeIdHelper", "classtesting_1_1internal_1_1_type_id_helper.html", null ],
        [ "TypeWithSize", "classtesting_1_1internal_1_1_type_with_size.html", "classtesting_1_1internal_1_1_type_with_size" ],
        [ "TypeWithSize< 4 >", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4.html", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4" ],
        [ "TypeWithSize< 8 >", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4.html", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4" ],
        [ "UniversalPrinter", "classtesting_1_1internal_1_1_universal_printer.html", null ],
        [ "UniversalPrinter< T & >", "classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalPrinter< T[N]>", "classtesting_1_1internal_1_1_universal_printer_3_01_t_0f_n_0e_4.html", null ],
        [ "UniversalTersePrinter", "classtesting_1_1internal_1_1_universal_terse_printer.html", null ],
        [ "UniversalTersePrinter< char * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01char_01_5_01_4.html", null ],
        [ "UniversalTersePrinter< const char * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char_01_5_01_4.html", null ],
        [ "UniversalTersePrinter< T & >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalTersePrinter< T[N]>", "classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_0f_n_0e_4.html", null ],
        [ "UniversalTersePrinter< wchar_t * >", "classtesting_1_1internal_1_1_universal_terse_printer_3_01wchar__t_01_5_01_4.html", null ],
        [ "ValueArray1", "classtesting_1_1internal_1_1_value_array1.html", "classtesting_1_1internal_1_1_value_array1" ],
        [ "ValueArray10", "classtesting_1_1internal_1_1_value_array10.html", "classtesting_1_1internal_1_1_value_array10" ],
        [ "ValueArray11", "classtesting_1_1internal_1_1_value_array11.html", "classtesting_1_1internal_1_1_value_array11" ],
        [ "ValueArray12", "classtesting_1_1internal_1_1_value_array12.html", "classtesting_1_1internal_1_1_value_array12" ],
        [ "ValueArray13", "classtesting_1_1internal_1_1_value_array13.html", "classtesting_1_1internal_1_1_value_array13" ],
        [ "ValueArray14", "classtesting_1_1internal_1_1_value_array14.html", "classtesting_1_1internal_1_1_value_array14" ],
        [ "ValueArray15", "classtesting_1_1internal_1_1_value_array15.html", "classtesting_1_1internal_1_1_value_array15" ],
        [ "ValueArray16", "classtesting_1_1internal_1_1_value_array16.html", "classtesting_1_1internal_1_1_value_array16" ],
        [ "ValueArray17", "classtesting_1_1internal_1_1_value_array17.html", "classtesting_1_1internal_1_1_value_array17" ],
        [ "ValueArray18", "classtesting_1_1internal_1_1_value_array18.html", "classtesting_1_1internal_1_1_value_array18" ],
        [ "ValueArray19", "classtesting_1_1internal_1_1_value_array19.html", "classtesting_1_1internal_1_1_value_array19" ],
        [ "ValueArray2", "classtesting_1_1internal_1_1_value_array2.html", "classtesting_1_1internal_1_1_value_array2" ],
        [ "ValueArray20", "classtesting_1_1internal_1_1_value_array20.html", "classtesting_1_1internal_1_1_value_array20" ],
        [ "ValueArray21", "classtesting_1_1internal_1_1_value_array21.html", "classtesting_1_1internal_1_1_value_array21" ],
        [ "ValueArray22", "classtesting_1_1internal_1_1_value_array22.html", "classtesting_1_1internal_1_1_value_array22" ],
        [ "ValueArray23", "classtesting_1_1internal_1_1_value_array23.html", "classtesting_1_1internal_1_1_value_array23" ],
        [ "ValueArray24", "classtesting_1_1internal_1_1_value_array24.html", "classtesting_1_1internal_1_1_value_array24" ],
        [ "ValueArray25", "classtesting_1_1internal_1_1_value_array25.html", "classtesting_1_1internal_1_1_value_array25" ],
        [ "ValueArray26", "classtesting_1_1internal_1_1_value_array26.html", "classtesting_1_1internal_1_1_value_array26" ],
        [ "ValueArray27", "classtesting_1_1internal_1_1_value_array27.html", "classtesting_1_1internal_1_1_value_array27" ],
        [ "ValueArray28", "classtesting_1_1internal_1_1_value_array28.html", "classtesting_1_1internal_1_1_value_array28" ],
        [ "ValueArray29", "classtesting_1_1internal_1_1_value_array29.html", "classtesting_1_1internal_1_1_value_array29" ],
        [ "ValueArray3", "classtesting_1_1internal_1_1_value_array3.html", "classtesting_1_1internal_1_1_value_array3" ],
        [ "ValueArray30", "classtesting_1_1internal_1_1_value_array30.html", "classtesting_1_1internal_1_1_value_array30" ],
        [ "ValueArray31", "classtesting_1_1internal_1_1_value_array31.html", "classtesting_1_1internal_1_1_value_array31" ],
        [ "ValueArray32", "classtesting_1_1internal_1_1_value_array32.html", "classtesting_1_1internal_1_1_value_array32" ],
        [ "ValueArray33", "classtesting_1_1internal_1_1_value_array33.html", "classtesting_1_1internal_1_1_value_array33" ],
        [ "ValueArray34", "classtesting_1_1internal_1_1_value_array34.html", "classtesting_1_1internal_1_1_value_array34" ],
        [ "ValueArray35", "classtesting_1_1internal_1_1_value_array35.html", "classtesting_1_1internal_1_1_value_array35" ],
        [ "ValueArray36", "classtesting_1_1internal_1_1_value_array36.html", "classtesting_1_1internal_1_1_value_array36" ],
        [ "ValueArray37", "classtesting_1_1internal_1_1_value_array37.html", "classtesting_1_1internal_1_1_value_array37" ],
        [ "ValueArray38", "classtesting_1_1internal_1_1_value_array38.html", "classtesting_1_1internal_1_1_value_array38" ],
        [ "ValueArray39", "classtesting_1_1internal_1_1_value_array39.html", "classtesting_1_1internal_1_1_value_array39" ],
        [ "ValueArray4", "classtesting_1_1internal_1_1_value_array4.html", "classtesting_1_1internal_1_1_value_array4" ],
        [ "ValueArray40", "classtesting_1_1internal_1_1_value_array40.html", "classtesting_1_1internal_1_1_value_array40" ],
        [ "ValueArray41", "classtesting_1_1internal_1_1_value_array41.html", "classtesting_1_1internal_1_1_value_array41" ],
        [ "ValueArray42", "classtesting_1_1internal_1_1_value_array42.html", "classtesting_1_1internal_1_1_value_array42" ],
        [ "ValueArray43", "classtesting_1_1internal_1_1_value_array43.html", "classtesting_1_1internal_1_1_value_array43" ],
        [ "ValueArray44", "classtesting_1_1internal_1_1_value_array44.html", "classtesting_1_1internal_1_1_value_array44" ],
        [ "ValueArray45", "classtesting_1_1internal_1_1_value_array45.html", "classtesting_1_1internal_1_1_value_array45" ],
        [ "ValueArray46", "classtesting_1_1internal_1_1_value_array46.html", "classtesting_1_1internal_1_1_value_array46" ],
        [ "ValueArray47", "classtesting_1_1internal_1_1_value_array47.html", "classtesting_1_1internal_1_1_value_array47" ],
        [ "ValueArray48", "classtesting_1_1internal_1_1_value_array48.html", "classtesting_1_1internal_1_1_value_array48" ],
        [ "ValueArray49", "classtesting_1_1internal_1_1_value_array49.html", "classtesting_1_1internal_1_1_value_array49" ],
        [ "ValueArray5", "classtesting_1_1internal_1_1_value_array5.html", "classtesting_1_1internal_1_1_value_array5" ],
        [ "ValueArray50", "classtesting_1_1internal_1_1_value_array50.html", "classtesting_1_1internal_1_1_value_array50" ],
        [ "ValueArray6", "classtesting_1_1internal_1_1_value_array6.html", "classtesting_1_1internal_1_1_value_array6" ],
        [ "ValueArray7", "classtesting_1_1internal_1_1_value_array7.html", "classtesting_1_1internal_1_1_value_array7" ],
        [ "ValueArray8", "classtesting_1_1internal_1_1_value_array8.html", "classtesting_1_1internal_1_1_value_array8" ],
        [ "ValueArray9", "classtesting_1_1internal_1_1_value_array9.html", "classtesting_1_1internal_1_1_value_array9" ],
        [ "ValuesInIteratorRangeGenerator", "classtesting_1_1internal_1_1_values_in_iterator_range_generator.html", "classtesting_1_1internal_1_1_values_in_iterator_range_generator" ],
        [ "VoidT", "structtesting_1_1internal_1_1_void_t.html", "structtesting_1_1internal_1_1_void_t" ],
        [ "WrapPrinterType", "structtesting_1_1internal_1_1_wrap_printer_type.html", null ]
      ] ],
      [ "internal2", "namespacetesting_1_1internal2.html", [
        [ "TypeWithoutFormatter", "classtesting_1_1internal2_1_1_type_without_formatter.html", null ],
        [ "TypeWithoutFormatter< T, kConvertibleToInteger >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_convertible_to_integer_01_4.html", null ],
        [ "TypeWithoutFormatter< T, kProtobuf >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_protobuf_01_4.html", null ]
      ] ],
      [ "EmptyTestEventListener", "classtesting_1_1_empty_test_event_listener.html", "classtesting_1_1_empty_test_event_listener" ],
      [ "Environment", "classtesting_1_1_environment.html", "classtesting_1_1_environment" ],
      [ "Message", "classtesting_1_1_message.html", "classtesting_1_1_message" ],
      [ "PrintToStringParamName", "structtesting_1_1_print_to_string_param_name.html", "structtesting_1_1_print_to_string_param_name" ],
      [ "ScopedTrace", "classtesting_1_1_scoped_trace.html", "classtesting_1_1_scoped_trace" ],
      [ "Test", "classtesting_1_1_test.html", "classtesting_1_1_test" ],
      [ "TestCase", "classtesting_1_1_test_case.html", "classtesting_1_1_test_case" ],
      [ "TestEventListener", "classtesting_1_1_test_event_listener.html", "classtesting_1_1_test_event_listener" ],
      [ "TestEventListeners", "classtesting_1_1_test_event_listeners.html", "classtesting_1_1_test_event_listeners" ],
      [ "TestInfo", "classtesting_1_1_test_info.html", "classtesting_1_1_test_info" ],
      [ "TestParamInfo", "structtesting_1_1_test_param_info.html", "structtesting_1_1_test_param_info" ],
      [ "TestProperty", "classtesting_1_1_test_property.html", "classtesting_1_1_test_property" ],
      [ "TestResult", "classtesting_1_1_test_result.html", "classtesting_1_1_test_result" ],
      [ "TestWithParam", "classtesting_1_1_test_with_param.html", null ],
      [ "UnitTest", "classtesting_1_1_unit_test.html", "classtesting_1_1_unit_test" ],
      [ "WithParamInterface", "classtesting_1_1_with_param_interface.html", "classtesting_1_1_with_param_interface" ]
    ] ],
    [ "tracesListener", "namespacetraces_listener.html", [
      [ "ByteUtil", "classtraces_listener_1_1_byte_util.html", null ],
      [ "CmdLineServer", "classtraces_listener_1_1_cmd_line_server.html", null ],
      [ "DataThread", "classtraces_listener_1_1_data_thread.html", "classtraces_listener_1_1_data_thread" ],
      [ "LogDataThread", "classtraces_listener_1_1_log_data_thread.html", "classtraces_listener_1_1_log_data_thread" ],
      [ "ModuleFilter", "classtraces_listener_1_1_module_filter.html", "classtraces_listener_1_1_module_filter" ],
      [ "ProgFilter", "classtraces_listener_1_1_prog_filter.html", "classtraces_listener_1_1_prog_filter" ],
      [ "TraceMessage", "classtraces_listener_1_1_trace_message.html", "classtraces_listener_1_1_trace_message" ],
      [ "TracesDataThread", "classtraces_listener_1_1_traces_data_thread.html", "classtraces_listener_1_1_traces_data_thread" ],
      [ "TracesDecoder", "classtraces_listener_1_1_traces_decoder.html", null ],
      [ "TracesFilter", "classtraces_listener_1_1_traces_filter.html", "classtraces_listener_1_1_traces_filter" ],
      [ "TracesListenerServer", "classtraces_listener_1_1_traces_listener_server.html", "classtraces_listener_1_1_traces_listener_server" ],
      [ "TracesObserver", "classtraces_listener_1_1_traces_observer.html", "classtraces_listener_1_1_traces_observer" ]
    ] ],
    [ "udt", "namespaceudt.html", [
      [ "address", "structudt_1_1address.html", "structudt_1_1address" ],
      [ "age", "structudt_1_1age.html", "structudt_1_1age" ],
      [ "contact", "structudt_1_1contact.html", "structudt_1_1contact" ],
      [ "contact_book", "structudt_1_1contact__book.html", "structudt_1_1contact__book" ],
      [ "legacy_type", "structudt_1_1legacy__type.html", "structudt_1_1legacy__type" ],
      [ "name", "structudt_1_1name.html", "structudt_1_1name" ],
      [ "non_pod", "structudt_1_1non__pod.html", "structudt_1_1non__pod" ],
      [ "person", "structudt_1_1person.html", "structudt_1_1person" ],
      [ "small_pod", "structudt_1_1small__pod.html", "structudt_1_1small__pod" ]
    ] ],
    [ "adl_serializer", "structadl__serializer.html", null ],
    [ "adl_serializer< std::optional< T > >", "structadl__serializer_3_01std_1_1optional_3_01_t_01_4_01_4.html", null ],
    [ "alt_string", "classalt__string.html", "classalt__string" ],
    [ "another_adl_serializer", "structanother__adl__serializer.html", null ],
    [ "array", "classarray.html", null ],
    [ "Bar", "class_bar.html", null ],
    [ "basic_json", "classbasic__json.html", "classbasic__json" ],
    [ "BasicErrors", "class_basic_errors.html", "class_basic_errors" ],
    [ "byte_container_with_subtype", "classbyte__container__with__subtype.html", "classbyte__container__with__subtype" ],
    [ "CommunicationErrors", "class_communication_errors.html", "class_communication_errors" ],
    [ "Data", "struct_data.html", "struct_data" ],
    [ "ExtendedErrors", "class_extended_errors.html", "class_extended_errors" ],
    [ "FileTransport", "class_file_transport.html", "class_file_transport" ],
    [ "Foo", "class_foo.html", "class_foo" ],
    [ "FooAlloc", "class_foo_alloc.html", null ],
    [ "FooBar", "class_foo_bar.html", "class_foo_bar" ],
    [ "for_3171_base", "structfor__3171__base.html", "structfor__3171__base" ],
    [ "for_3171_derived", "structfor__3171__derived.html", "structfor__3171__derived" ],
    [ "for_3204_bar", "structfor__3204__bar.html", "structfor__3204__bar" ],
    [ "for_3204_foo", "structfor__3204__foo.html", "structfor__3204__foo" ],
    [ "for_3333", "structfor__3333.html", "structfor__3333" ],
    [ "json_metadata", "classjson__metadata.html", "classjson__metadata" ],
    [ "json_pointer", "classjson__pointer.html", "classjson__pointer" ],
    [ "json_sax", "structjson__sax.html", "structjson__sax" ],
    [ "JsonParameters", "class_json_parameters.html", null ],
    [ "JsonRPCClient", "class_json_r_p_c_client.html", "class_json_r_p_c_client" ],
    [ "JsonRPCServer", "class_json_r_p_c_server.html", "class_json_r_p_c_server" ],
    [ "Link", "class_link.html", "class_link" ],
    [ "Message", "struct_message.html", "struct_message" ],
    [ "MessageHeader", "struct_message_header.html", "struct_message_header" ],
    [ "my_allocator", "classmy__allocator.html", "classmy__allocator" ],
    [ "NonDefaultConstructible", "struct_non_default_constructible.html", "struct_non_default_constructible" ],
    [ "NotSerializableData", "struct_not_serializable_data.html", "struct_not_serializable_data" ],
    [ "number_float", "classnumber__float.html", null ],
    [ "number_integer", "classnumber__integer.html", null ],
    [ "number_unsigned", "classnumber__unsigned.html", null ],
    [ "object", "classobject.html", null ],
    [ "ordered_map", "structordered__map.html", "structordered__map" ],
    [ "Parameter", "struct_parameter.html", "struct_parameter" ],
    [ "ParameterHeader", "struct_parameter_header.html", "struct_parameter_header" ],
    [ "RemoteProcedureCall", "class_remote_procedure_call.html", "class_remote_procedure_call" ],
    [ "ReturnValue", "class_return_value.html", "class_return_value" ],
    [ "RPCClient", "class_r_p_c_client.html", "class_r_p_c_client" ],
    [ "RPCServer", "class_r_p_c_server.html", "class_r_p_c_server" ],
    [ "sax_event_consumer", "classsax__event__consumer.html", "classsax__event__consumer" ],
    [ "sax_no_exception", "classsax__no__exception.html", "classsax__no__exception" ],
    [ "Semaphore", "class_semaphore.html", "class_semaphore" ],
    [ "string", "classstring.html", null ],
    [ "TcpTransport", "class_tcp_transport.html", "class_tcp_transport" ],
    [ "TestApplication", "class_test_application.html", null ],
    [ "Thread", "class_thread.html", "class_thread" ],
    [ "trait_test_arg", "structtrait__test__arg.html", "structtrait__test__arg" ],
    [ "Transport", "class_transport.html", "class_transport" ],
    [ "visitor_adaptor", "classvisitor__adaptor.html", "classvisitor__adaptor" ],
    [ "visitor_adaptor_with_metadata", "classvisitor__adaptor__with__metadata.html", "classvisitor__adaptor__with__metadata" ]
];