var dir_06fa8a48edecc98cd628892654d849f3 =
[
    [ "App.java", "_app_8java.html", "_app_8java" ],
    [ "AppUtil.java", "_app_util_8java.html", "_app_util_8java" ],
    [ "ARGBColorPanel.java", "_a_r_g_b_color_panel_8java.html", "_a_r_g_b_color_panel_8java" ],
    [ "ARGBColorPicker.java", "_a_r_g_b_color_picker_8java.html", "_a_r_g_b_color_picker_8java" ],
    [ "ColorCircle.java", "_color_circle_8java.html", "_color_circle_8java" ],
    [ "ContentFrame.java", "_content_frame_8java.html", "_content_frame_8java" ],
    [ "ContentFrameEnsemble.java", "_content_frame_ensemble_8java.html", "_content_frame_ensemble_8java" ],
    [ "ContentFrameVE.java", "_content_frame_v_e_8java.html", "_content_frame_v_e_8java" ],
    [ "DecimalDigitsTextField.java", "_decimal_digits_text_field_8java.html", "_decimal_digits_text_field_8java" ],
    [ "FilePicker.java", "_file_picker_8java.html", "_file_picker_8java" ],
    [ "FindDialog.java", "_find_dialog_8java.html", "_find_dialog_8java" ],
    [ "FindPanel.java", "_find_panel_8java.html", "_find_panel_8java" ],
    [ "GlobalSettingsPanel.java", "_global_settings_panel_8java.html", "_global_settings_panel_8java" ],
    [ "LineNumberDialog.java", "_line_number_dialog_8java.html", "_line_number_dialog_8java" ],
    [ "LineNumberDialogVE.java", "_line_number_dialog_v_e_8java.html", "_line_number_dialog_v_e_8java" ],
    [ "LookAndFeelComboBox.java", "_look_and_feel_combo_box_8java.html", "_look_and_feel_combo_box_8java" ],
    [ "MainFrame.java", "_main_frame_8java.html", "_main_frame_8java" ],
    [ "MainFrameVE.java", "_main_frame_v_e_8java.html", "_main_frame_v_e_8java" ],
    [ "ModIdDefinitionDialog.java", "_mod_id_definition_dialog_8java.html", "_mod_id_definition_dialog_8java" ],
    [ "ModIdDefinitionDialogVE.java", "_mod_id_definition_dialog_v_e_8java.html", "_mod_id_definition_dialog_v_e_8java" ],
    [ "ModIdTable.java", "_mod_id_table_8java.html", "_mod_id_table_8java" ],
    [ "ModIdTableModel.java", "_mod_id_table_model_8java.html", "_mod_id_table_model_8java" ],
    [ "ModIdTableTransferHandler.java", "_mod_id_table_transfer_handler_8java.html", "_mod_id_table_transfer_handler_8java" ],
    [ "MultiColoredTextArea.java", "_multi_colored_text_area_8java.html", "_multi_colored_text_area_8java" ],
    [ "PopupMouseListener.java", "_popup_mouse_listener_8java.html", null ],
    [ "ProgDefinitionDialog.java", "_prog_definition_dialog_8java.html", "_prog_definition_dialog_8java" ],
    [ "ProgDefinitionDialogVE.java", "_prog_definition_dialog_v_e_8java.html", "_prog_definition_dialog_v_e_8java" ],
    [ "ProgTable.java", "_prog_table_8java.html", "_prog_table_8java" ],
    [ "ProgTableModel.java", "_prog_table_model_8java.html", "_prog_table_model_8java" ],
    [ "ProgTableTransferHandler.java", "_prog_table_transfer_handler_8java.html", "_prog_table_transfer_handler_8java" ],
    [ "Strings.java", "_strings_8java.html", "_strings_8java" ],
    [ "TablePopupMouseListener.java", "_table_popup_mouse_listener_8java.html", null ],
    [ "WindowNameDialog.java", "_window_name_dialog_8java.html", "_window_name_dialog_8java" ],
    [ "WindowNameDialogVE.java", "_window_name_dialog_v_e_8java.html", "_window_name_dialog_v_e_8java" ],
    [ "WindowSettingsDialog.java", "_window_settings_dialog_8java.html", "_window_settings_dialog_8java" ]
];