CXX = g++
CXX_FLAGS = -std=c++11 -fPIC -ggdb
LXX_FLAGS = -L ../Transport -l Transport -L ../Thread -l Thread -L ../RPC -l RPC -L ../EClient -l EClient -l pthread
IXX_FLAGS = -I ../Transport -I ../Thread -I ../RPC -I ../EClient
OBJECTS := $(patsubst %.cpp,%.o, $(wildcard *.cpp))

all : test

test :
	$(CXX) -o test test.cpp $(CXX_FLAGS) $(IXX_FLAGS) $(LXX_FLAGS)

clean :
	-rm -rf test test.o 2>/dev/null

rebuild : clean test

	

	
